<a href="https://colab.research.google.com/github/AbhishekSaini1101/Colab/blob/main/PythonPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
x = 34
print(id(x)) #Here id is used to show the location of variable

134513856513296


In [2]:
x = 34; y = 3.4

print(x+y)
#Implicit type conversion ( when language itself convert the type)
#Here 34 is int and 3.4 is float
#When we added int + float we got the ans in Int

Number = int(input("Enter any number"))
#Input function takes input in string from user.
#We convert Str to int
#Explicit type conversion when user tells language to convert data type.

37.4
Enter any number6556


In [3]:
#One dimensional List
L1 = [1, 2,3,4]
print(L1[2])

#Two dimensional list
#List inside list
L2 = [1,2,[3,4], [5,6,7]]
print(L2[0])
print(L2[3][0])

TempL = L2[3]
print(TempL[0])

#Multi Dimensional List
L4 = [[0,1],[[2,3],[4,5]]]
#we need to print 4 from List
print(L4[1][1][0])

3
1
5
5
4


NUMPY

In [4]:
import numpy as np

L = [1,2,3,4,5,6,7,8,9,10]
print(L)

arr = np.array(L)
print(arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
type(arr)

numpy.ndarray

In [6]:
L1 = [1,2,3,4,5]
L2 = [6,7,8,9,10]
L3 = [11,12,13,14,15]

#arr = np.array(L1)
arr = np.array([L1, L2, L3])

In [7]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
arr.shape

(3, 5)

In [9]:
  arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

# --------**-Indexing**----------------

In [10]:
#----- 1D ARRAY
L = [1,2,3,4,5,6,7,8,9,10]

ar = np.array(L)

ar[2]


3

In [11]:
#-----2D ARRAY

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
arr[1:,3:]

array([[ 9, 10],
       [14, 15]])

In [13]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [14]:
arr[1,1:4]

array([7, 8, 9])

In [15]:
#-----Arange-----

arr = np.arange(0,20, step = 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.linspace(1,10,50)


array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [17]:
#---- Broadcasting -----

arr[3:] = 300
arr

array([  0,   2,   4, 300, 300, 300, 300, 300, 300, 300])

In [18]:
#---- Copy array ----

arr1 = arr.copy()

In [19]:
print(arr)
arr1[3:] = 1000
print(arr1)

[  0   2   4 300 300 300 300 300 300 300]
[   0    2    4 1000 1000 1000 1000 1000 1000 1000]


In [20]:
# Some conditions very useful in Exploratory Data Analysis

value = 2
arr < 2

array([ True, False, False, False, False, False, False, False, False,
       False])

In [21]:
#Create array and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
arr[arr<300]

array([0, 2, 4])

In [23]:
np.ones(4)

array([1., 1., 1., 1.])